version: 0.0
os: linux
 
files:
  - source: /
    destination: /var/www/html/ohana/

hooks:
  ApplicationStop:
    - location: scripts/
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
